[View in Colaboratory](https://colab.research.google.com/github/sumitdua10/Seq-Networks/blob/master/RNN_Example.ipynb)

In [0]:

#import numpy as np
import tensorflow as tf
sess = tf.Session()

from keras.models import Sequential, Model
from keras.layers import Dense, Activation, Dropout, LSTM, GRU, Input, Embedding, RNN, SimpleRNNCell, SimpleRNN


In [2]:
LSTM_CELL_SIZE = 4  # output size (dimension), which is same as hidden size in the cell

lstm_cell = tf.contrib.rnn.BasicLSTMCell(LSTM_CELL_SIZE, state_is_tuple=True)
rnn_cell = tf.contrib.rnn.
state = (tf.zeros([2,LSTM_CELL_SIZE]),)*2
print(state)

sample_input = tf.constant([[1,2,3,4,3,2],[3,2,2,2,2,2]],dtype=tf.float32)
print (sess.run(sample_input))


Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
(<tf.Tensor 'zeros:0' shape=(2, 4) dtype=float32>, <tf.Tensor 'zeros:0' shape=(2, 4) dtype=float32>)
[[1. 2. 3. 4. 3. 2.]
 [3. 2. 2. 2. 2. 2.]]


In [30]:
import numpy as np
T = 8
D = 2
M = 5

X = np.random.randn(1, T, D)
print(X.shape)

def rnn_ret_seq_false():
  input_ = Input(shape=(T, D))
  rnn = SimpleRNN(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print("o:", o)
  print("h:", h)
  #print("c:", c)
  print("Model summary:")
  print(model.summary())

  
def rnn_ret_seq_true():
  input_ = Input(shape=(T, D))
  rnn = SimpleRNN(M, return_state=True,  return_sequences=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print("o:", o)
  print("h:", h)
  #print("c:", c)
  print("Model summary:")
  print(model.summary())


def lstm_ret_seq_false():
  input_ = Input(shape=(T, D))
  rnn = LSTM(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print("o:", o)
  print("h:", h)
  print("c:", c)
  print("Model summary:")
  print(model.summary())


def lstm_ret_seq_true():
  input_ = Input(shape=(T, D))
  rnn = LSTM(M, return_state=True, return_sequences=True)
  # rnn = GRU(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print("o:", o)
  print("h:", h)
  print("c:", c)
  print("Model summary:")
  print(model.summary())


def gru_ret_seq_false():
  input_ = Input(shape=(T, D))
  rnn = GRU(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print("o:", o)
  print("h:", h)
  print("Model summary:")
  print(model.summary())


def gru_ret_seq_true():
  input_ = Input(shape=(T, D))
  rnn = GRU(M, return_state=True, return_sequences=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print("o:", o)
  print("h:", h)
  print("Model summary:")
  print(model.summary())
  

(2, 8, 2)


In [32]:


print("RNN ret seq false:")
rnn_ret_seq_false()

#print("\nRNN ret seq true:")
#rnn_ret_seq_true()

#print("lstm ret seq false:")
#lstm_ret_seq_false()
#print("lstm ret seq true:")
#lstm_ret_seq_true()
print("gru ret seq false:")
gru_ret_seq_false()
#print_ret_seq_true("gru ret seq true:")
#gru2()

RNN ret seq false:
o: [[-0.63451695  0.58201516 -0.8332197   0.8778295   0.1722003 ]
 [-0.00858542 -0.579077    0.42863792 -0.4287584   0.12065346]]
h: [[-0.63451695  0.58201516 -0.8332197   0.8778295   0.1722003 ]
 [-0.00858542 -0.579077    0.42863792 -0.4287584   0.12065346]]
Model summary:
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_18 (InputLayer)        (None, 8, 2)              0         
_________________________________________________________________
simple_rnn_15 (SimpleRNN)    [(None, 5), (None, 5)]    40        
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________
None
gru ret seq false:
o: [[-0.09803301  0.0238734  -0.00738997 -0.09977927  0.04441949]
 [-0.28214934  0.12102765  0.27571824 -0.08635886  0.08339989]]
h: [[-0.09803301  0.0238734  -0.00738997 -0.09977927  0.04441949]
 [-0.28214934  0.12102765  0